/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as EquipasRouteImport } from './routes/equipas'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin.calendario'
import { Route as AuthenticatedAdminEquipasRouteImport } from './routes/_authenticated/admin.equipas'
import { Route as AuthenticatedAdminResultadosRouteImport } from './routes/_authenticated/admin.resultados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipasRoute = EquipasRouteImport.update({
  id: '/equipas',
  path: '/equipas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipasRoute =
  AuthenticatedAdminEquipasRouteImport.update({
    id: '/equipas',
    path: '/equipas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultadosRoute =
  AuthenticatedAdminResultadosRouteImport.update({
    id: '/resultados',
    path: '/resultados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/equipas': typeof AuthenticatedAdminEquipasRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias': typeof NoticiasIndexRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/equipas': typeof AuthenticatedAdminEquipasRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/noticias/$id': typeof NoticiasIdRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/equipas': typeof AuthenticatedAdminEquipasRoute
  '/_authenticated/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/admin'
    | '/noticias/$id'
    | '/noticias/'
    | '/admin/calendario'
    | '/admin/equipas'
    | '/admin/resultados'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/noticias/$id'
    | '/noticias'
    | '/admin/calendario'
    | '/admin/equipas'
    | '/admin/resultados'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/_authenticated/admin'
    | '/noticias/$id'
    | '/noticias/'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/equipas'
    | '/_authenticated/admin/resultados'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  EquipasRoute: typeof EquipasRoute
  ResultadosRoute: typeof ResultadosRoute
  NoticiasIdRoute: typeof NoticiasIdRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipas': {
      id: '/equipas'
      path: '/equipas'
      fullPath: '/equipas'
      preLoaderRoute: typeof EquipasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipas': {
      id: '/_authenticated/admin/equipas'
      path: '/equipas'
      fullPath: '/admin/equipas'
      preLoaderRoute: typeof AuthenticatedAdminEquipasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resultados': {
      id: '/_authenticated/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AuthenticatedAdminResultadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminEquipasRoute: typeof AuthenticatedAdminEquipasRoute
  AuthenticatedAdminResultadosRoute: typeof AuthenticatedAdminResultadosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminEquipasRoute: AuthenticatedAdminEquipasRoute,
  AuthenticatedAdminResultadosRoute: AuthenticatedAdminResultadosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  EquipasRoute: EquipasRoute,
  ResultadosRoute: ResultadosRoute,
  NoticiasIdRoute: NoticiasIdRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
