/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as EquipasRouteImport } from './routes/equipas'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipasRoute = EquipasRouteImport.update({
  id: '/equipas',
  path: '/equipas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/equipas': typeof EquipasRoute
  '/resultados': typeof ResultadosRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/equipas'
    | '/resultados'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  EquipasRoute: typeof EquipasRoute
  ResultadosRoute: typeof ResultadosRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipas': {
      id: '/equipas'
      path: '/equipas'
      fullPath: '/equipas'
      preLoaderRoute: typeof EquipasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  EquipasRoute: EquipasRoute,
  ResultadosRoute: ResultadosRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
